version: '3'
services:
  db:
    image: mysql:5.7.35
    container_name: eater_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - '5000:3306'
    volumes:
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  app:
    tty: true
    stdin_open: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/MyCurryApp
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-volume: